### ISSUE TITLE
Thumbnail preview not showing

### ISSUE THREAD

**Issue by Fzoltan87** [StanislavDK/PHPFilemanager4Summernote#1]
Hy, Thumbnail preview not showing in list.

![example-list](https://user-images.githubusercontent.com/16391914/103347276-d2602c00-4a96-11eb-932b-3e5dbab295da.png)

![example](https://user-images.githubusercontent.com/16391914/103347260-c6746a00-4a96-11eb-8cb9-be18bc117a79.jpg)

**Comment by StanislavDK** [comment]
Hello. Check the rights (chmod) on thumb.php. Also check the error of the file "thumb.php" request in the debugger in the network tab  of the browser.
